name: Testing workflow variables

on: workflow_dispatch

env:
  cloud: 'google-cloud'
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      greeting: 'Hello,'
    steps:
      - name: Say hello, it's a Monday
        run: echo "${{ env.greeting }} ${{ env.first_name }}! is using ${{env.cloud}}."
        env:
          first_name: 'John'
