name: UI Automation using WebDriver and Java CI with Maven
on: workflow_dispatch
jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
      - name: pull the project into the runner
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup chrome
        uses: browser-actions/setup-chrome@v1
        with:
          # The Google Chrome/Chromium version to install and use.
          chrome-version: "latest"
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
          step: restore
      - name: Run the web test
        run: mvn clean test -Dtest=ContactUsTest
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
            step: save


